name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
            toolchain: stable
    - uses: Swatinem/rust-cache@v1
    - name: rust-cargo
      uses: actions-rs/cargo@v1.0.1
      with:
        command: build
    - name: rust-cargo
      uses: actions-rs/cargo@v1.0.1
      with:
        command: test

  nixtest:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - uses: cachix/cachix-action@v12
        with:
          name: cftail
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build -L
      - run: ./result/bin/cftail --help
